<?php
// Aktuelle Seite ermitteln
$current_page = $_GET['page'] ?? '';

?>

<aside>
    <div class="sidebar" style="height:100%;">
        <div class="sidebar-header">
            <div class="logo">
                <a href="index.php">
                    <img src="<?= htmlspecialchars($helper->getSiteUrl('admin/assets/images/logo-text-bg.jpg'), ENT_QUOTES, 'UTF-8'); ?>" 
                        alt="marques CMS" style="max-width:240px;" />
                </a>
                <!-- marques CMS -->
            </div>
            <p>
                <small>Angemeldet als:</small> 
                <?= htmlspecialchars($user->getCurrentDisplayName()); ?>
            </p>
        </div>
        <nav class="nav-menu">
            <div class="nav-item">
                <a href="index.php"
                    class="nav-link <?= (!isset($current_page) || $current_page === '' || $current_page === 'dashboard') ? 'active' : ''; ?>">
                    <?= $this->renderIcon('gauge', 'nav-menu-icon', '24'); ?>
                    Dashboard
                </a>
            </div>
            <div class="nav-item">
                <a href="<?= htmlspecialchars($helper->appQueryParam('page=pages'), ENT_QUOTES, 'UTF-8'); ?>"
                    class="nav-link <?= $current_page === 'pages' || $current_page === 'page-edit' ? 'active' : ''; ?>">
                    <?= $this->renderIcon('files', 'nav-menu-icon', '24'); ?>
                    Seiten
                </a>
            </div>
            <div class="nav-item">
                <a href="<?= htmlspecialchars($helper->appQueryParam('page=navigation'), ENT_QUOTES, 'UTF-8'); ?>"
                    class="nav-link <?= $current_page === 'navigation' ? 'active' : ''; ?>">
                    <?= $this->renderIcon('menu-3', 'nav-menu-icon', '24'); ?>
                    Menüs
                </a>
            </div>
            <div class="nav-item">
                <a href="<?= htmlspecialchars($helper->appQueryParam('page=media'), ENT_QUOTES, 'UTF-8'); ?>"
                    class="nav-link <?= $current_page === 'media' ? 'active' : ''; ?>">
                    <?= $this->renderIcon('library-photo', 'nav-menu-icon', '24'); ?>
                    Medien
                </a>
            </div>
            <div class="nav-item">
                <a href="<?= htmlspecialchars($helper->appQueryParam('page=blog'), ENT_QUOTES, 'UTF-8'); ?>"
                    class="nav-link <?= $current_page === 'blog' || $current_page === 'blog-categories' || $current_page === 'blog-tags' || $current_page === 'blog-edit' ? 'active' : ''; ?>">
                    <?= $this->renderIcon('news', 'nav-menu-icon', '24'); ?>
                    Blog
                </a>
                <div class="nav-sub-item">
                    <a href="<?= htmlspecialchars($helper->appQueryParam('page=blog'), ENT_QUOTES, 'UTF-8'); ?>"
                        class="nav-link <?= $current_page === 'blog' ? 'active' : ''; ?>">
                        <?= $this->renderIcon('point', 'nav-menu-icon', '14'); ?>
                        Alle Beiträge
                    </a>
                </div>
                <div class="nav-sub-item">
                    <a href="<?= htmlspecialchars($helper->appQueryParam('page=blog-edit'), ENT_QUOTES, 'UTF-8'); ?>"
                        class="nav-link <?= $current_page === 'blog-edit' ? 'active' : ''; ?>">
                        <?= $this->renderIcon('point', 'nav-menu-icon', '14'); ?>
                        Neuer Beitrag
                    </a>
                </div>
                <div class="nav-sub-item">
                    <a href="<?= htmlspecialchars($helper->appQueryParam('page=blog-categories'), ENT_QUOTES, 'UTF-8'); ?>"
                        class="nav-link <?= $current_page === 'blog-categories' ? 'active' : ''; ?>">
                        <?= $this->renderIcon('point', 'nav-menu-icon', '14'); ?>
                        Kategorien
                    </a>
                </div>
                <div class="nav-sub-item">
                    <a href="<?= htmlspecialchars($helper->appQueryParam('page=blog-tags'), ENT_QUOTES, 'UTF-8'); ?>"
                        class="nav-link <?= $current_page === 'blog-tags' ? 'active' : ''; ?>">
                        <?= $this->renderIcon('point', 'nav-menu-icon', '14'); ?>
                        Tags
                    </a>
                </div>
            </div>
            <div class="nav-item">
                <a href="<?= htmlspecialchars($helper->appQueryParam('page=users'), ENT_QUOTES, 'UTF-8'); ?>"
                    class="nav-link <?= $current_page === 'users' || $current_page === 'user-edit' ? 'active' : ''; ?>">
                    <?= $this->renderIcon('users-group', 'nav-menu-icon', '24'); ?>
                    Benutzer
                </a>
            </div>
            <div class="nav-item">
                <a href="<?= htmlspecialchars($helper->appQueryParam('page=settings'), ENT_QUOTES, 'UTF-8'); ?>"
                    class="nav-link <?= $current_page === 'settings' ? 'active' : ''; ?>">
                    <?= $this->renderIcon('adjustments-cog', 'nav-menu-icon', '24'); ?>
                    Einstellungen
                </a>
            </div>
        </nav>
        <div class="sidebar-footer">
            <a href="?page=logout" class="admin-logout-link">
                <?= $this->renderIcon('currency-quetzal', 'nav-menu-icon', '24'); ?>
                Abmelden
            </a>
            <p>marques CMS v<?= MARQUES_VERSION; ?></p>
        </div>
    </div>
</aside>